language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.1
  - jruby-19mode
jdk:
  - oraclejdk8
notifications:
  email: false
virtualenv:
  system_site_packages: true
git:
  depth: 10
addons:
  apt:
    packages:
    - python-docutils
